package com.panelist_rm.panelist;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class cns_panelist implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public cns_panelist() {
    }




}