package com.panelist_rm.panelist;
//import java.lang;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class cns_panelist implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	public cns_panelist() {
	}


   private String country;
  private String business;
  private String data_source;
  private String data_frequency;
  private Long dml_version;
  private Long panelist_seqno;
  private Long bre_version;
  private Long data_year;
  private Long data_month;
  private Long data_week;
  private Long data_week_number;
  private Long data_day;
  private Long ppmonth;
  private Long ppweek;
  private String added_date;
  private String updated_date;
  private Long load_id;
  private java.util.List<java.lang.Long> primary_key;
  private Long panelist_id;
  private String projection_date;
  private String survey_start_date;
  private Long household_head;
  private Long age;
  private Long male_head_age;
  private Long female_head_age;
  private Long head_of_household_age;
  private Long survey_age;
  private Long gender;
  private Long survey_gender;
  private Long race;
  private Long hispanic;
  private Long ethnic_group;
  private Long marital_status;
  private Long education;
  private Long education_detail;
  private Long employment;
  private Long male_head_employment;
  private Long female_head_employment;
  private Long employment_status;
  private Long occupation;
  private Long male_head_occupation;
  private Long female_head_occupation;
  private Long male_head_education;
  private Long female_head_education;
  private Long buyer;
  private Long household_income;
  private Long household_size;
  private Long household_composition;
  private Long age_of_children;
  private Long life_cycle;
  private Long microvision;
  private Long prism;
  private Long spectra;
  private Long market_size;
  private Long cbsa_market_size;
  private Long pg_market_size;
  private Long state;
  private Long dma;
  private Long msa;
  private String postal_code;
  private Long group_number;
  private Long number_of_trackers;
  private Long number_of_trackers_6mos;
  private Long days_on_panel;
  private Long active_days_on_panel;
  private Long months_on_panel;
  private Long quality_score;
  private Long samsclub_segmentation;
  private Long walmart_segmentation;
  private Long internet_access;
  private Long computer_location;
  private Long connection_type;
  private Long operating_system;
  private Long pc_type;
  private Long work_at_home;
  private Long closed_custom_counter;
  private Long closed_tracker_counter;
  private Long cnr_counter;
  private Long mega_reclaim_counter;
  private Long proh_reclaim_counter;
  private Long inactive_reclaim_counter;
  private Long factors__projection_factor;
  private Long factors__routing_factor;
  private Long panelist_attr_0;
  private Long panelist_attr_1;
  private Long panelist_attr_2;
  private Long panelist_attr_3;
  private Long panelist_attr_4;
  private Long panelist_attr_5;
  private Long panelist_attr_6;
  private Long panelist_attr_7;
  private Long panelist_attr_8;
  private Long panelist_attr_9;
  private Long panelist_attr_10;
  private Long panelist_attr_11;
  private Long panelist_attr_12;
  private Long panelist_attr_13;
  private Long panelist_attr_14;
  private Long panelist_attr_15;
  private Long panelist_attr_16;
  private Long panelist_attr_17;
  private Long panelist_attr_18;
  private Long panelist_attr_19;
  private Long panelist_attr_20;
  private Long panelist_attr_21;
  private Long panelist_attr_22;
  private Long panelist_attr_23;
  private Long panelist_attr_24;
  private Long panelist_attr_25;
  private Long panelist_attr_26;
  private Long panelist_attr_27;
  private Long panelist_attr_28;
  private Long panelist_attr_29;
  private Long panelist_attr_30;
  private Long panelist_attr_31;
  private Long panelist_attr_32;
  private Long panelist_attr_33;
  private Long panelist_attr_34;
  private Long panelist_attr_35;
  private Long panelist_attr_36;
  private Long panelist_attr_37;
  private Long panelist_attr_38;
  private Long panelist_attr_39;
  private Long panelist_attr_40;
  private Long panelist_attr_41;
  private Long panelist_attr_42;
  private Long panelist_attr_43;
  private Long panelist_attr_44;
  private Long panelist_attr_45;
  private Long panelist_attr_46;
  private Long panelist_attr_47;
  private Long panelist_attr_48;
  private Long panelist_attr_49;
  private Long panelist_attr_50;
  private Long panelist_attr_51;
  private Long panelist_attr_52;
  private Long panelist_attr_53;
  private Long panelist_attr_54;
  private Long panelist_attr_55;
  private Long panelist_attr_56;
  private Long panelist_attr_57;
  private Long panelist_attr_58;
  private Long panelist_attr_59;
  private Long panelist_attr_60;
  private Long panelist_attr_61;
  private Long panelist_attr_62;
  private Long panelist_attr_63;
  private Long panelist_attr_64;
  private Long panelist_attr_65;
  private Long panelist_attr_66;
  private Long panelist_attr_67;
  private Long panelist_attr_68;
  private Long panelist_attr_69;
  private Long panelist_attr_70;
  private Long panelist_attr_71;
  private Long panelist_attr_72;
  private Long panelist_attr_73;
  private Long panelist_attr_74;
  private Long panelist_attr_75;
  private Long panelist_attr_76;
  private Long panelist_attr_77;
  private Long panelist_attr_78;
  private Long panelist_attr_79;
  private Long panelist_attr_80;
  private Long panelist_attr_81;
  private Long panelist_attr_82;
  private Long panelist_attr_83;
  private Long panelist_attr_84;
  private Long panelist_attr_85;
  private Long panelist_attr_86;
  private Long panelist_attr_87;
  private Long panelist_attr_88;
  private Long panelist_attr_89;
  private Long panelist_attr_90;
  private Long panelist_attr_91;
  private Long panelist_attr_92;
  private Long panelist_attr_93;
  private Long panelist_attr_94;
  private Long panelist_attr_95;
  private Long panelist_attr_96;
  private Long panelist_attr_97;
  private Long panelist_attr_98;
  private Long panelist_attr_99;
  private java.util.List<java.lang.Long> multi_choice_codes_01;
  private java.util.List<java.lang.Long> multi_choice_codes_02;
  private java.util.List<java.lang.Long> multi_choice_codes_03;
  private java.util.List<java.lang.Long> multi_choice_codes_04;
  private java.util.List<java.lang.Long> multi_choice_codes_05;
  private java.util.List<java.lang.Long> multi_choice_codes_06;
  private java.util.List<java.lang.Long> multi_choice_codes_07;
  private java.util.List<java.lang.Long> multi_choice_codes_08;
  private java.util.List<java.lang.Long> multi_choice_codes_09;
  private java.util.List<java.lang.Long> multi_choice_codes_10;
  private java.util.List<java.lang.Long> multi_choice_codes_11;
  private java.util.List<java.lang.Long> multi_choice_codes_12;
  private java.util.List<java.lang.Long> multi_choice_codes_13;
  private java.util.List<java.lang.Long> multi_choice_codes_14;
  private java.util.List<java.lang.Long> multi_choice_codes_15;
  private java.util.List<java.lang.Long> multi_choice_codes_16;
  private java.util.List<java.lang.Long> multi_choice_codes_17;
  private java.util.List<java.lang.Long> multi_choice_codes_18;
  private java.util.List<java.lang.Long> multi_choice_codes_19;
  private java.util.List<java.lang.Long> multi_choice_codes_20;
  private java.util.List<java.lang.Long> multi_choice_codes_21;
  private java.util.List<java.lang.Long> multi_choice_codes_22;
  private java.util.List<java.lang.Long> multi_choice_codes_23;
  private java.util.List<java.lang.Long> multi_choice_codes_24;
  private java.util.List<java.lang.Long> multi_choice_codes_25;
  private String questionnaire_values_01;
  private String questionnaire_values_02;
  private String questionnaire_values_03;
  private String reserved_fields__filler_1;
  private String extended_dml_flag;
  private String mail_date;
  private String confirmit_jobnum;
  private Long education_dim__level_0;
  private Long education_dim__level_1;
  private Long education_dim__level_2;
  private Long education_dim__level_3;
  private Long education_dim__level_4;
  private Long education_dim__level_5;
  private Long education_dim__level_6;
  private Long education_dim__level_7;
  private Long education_dim__level_8;
  private Long education_dim__level_9;
  private Long geo_dim__level_0;
  private Long geo_dim__level_1;
  private Long geo_dim__level_2;
  private Long geo_dim__level_3;
  private Long geo_dim__level_4;
  private Long geo_dim__level_5;
  private Long geo_dim__level_6;
  private Long geo_dim__level_7;
  private Long geo_dim__level_8;
  private Long geo_dim__level_9;
  private Long household_size_dim__level_0;
  private Long household_size_dim__level_1;
  private Long household_size_dim__level_2;
  private Long household_size_dim__level_3;
  private Long household_size_dim__level_4;
  private Long household_size_dim__level_5;
  private Long household_size_dim__level_6;
  private Long household_size_dim__level_7;
  private Long household_size_dim__level_8;
  private Long household_size_dim__level_9;
  private Long household_income_dim__level_0;
  private Long household_income_dim__level_1;
  private Long household_income_dim__level_2;
  private Long household_income_dim__level_3;
  private Long household_income_dim__level_4;
  private Long household_income_dim__level_5;
  private Long household_income_dim__level_6;
  private Long household_income_dim__level_7;
  private Long household_income_dim__level_8;
  private Long household_income_dim__level_9;
  private Long complete_flag;
  private Long status;
  private Long factor_values_0;
  private Long factor_values_1;
  private Long factor_values_2;
  private Long factor_values_3;
  private Long factor_values_4;
  private Long factor_values_5;
  private Long factor_values_6;
  private Long factor_values_7;
  private Long factor_values_8;
  private Long factor_values_9;
  private Long factor_values_10;
  private Long factor_values_11;
  private Long factor_values_12;
  private Long factor_values_13;
  private Long factor_values_14;
  private Long factor_values_15;
  private Long factor_values_16;
  private Long factor_values_17;
  private Long factor_values_18;
  private Long factor_values_19;
  private String cns_raw_values_0;
  private String cns_raw_values_1;
  private String cns_raw_values_2;
  private String cns_raw_values_3;
  private String cns_raw_values_4;
  private java.util.List<java.lang.Long> multi_choice_codes_27;
  private Long panelist_attr_100;
  private Long panelist_attr_101;
  private Long panelist_attr_102;
  private Long panelist_attr_103;
  private Long panelist_attr_104;
  private Long panelist_attr_105;
  private Long panelist_attr_106;
  private Long panelist_attr_107;
  private Long panelist_attr_108;
  private Long panelist_attr_109;
  private Long panelist_attr_110;
  private Long panelist_attr_111;
  private Long panelist_attr_112;
  private Long panelist_attr_113;
  private Long panelist_attr_114;
  private Long panelist_attr_115;
  private Long panelist_attr_116;
  private Long panelist_attr_117;
  private Long panelist_attr_118;
  private Long panelist_attr_119;
  private Long panelist_attr_120;
  private Long panelist_attr_121;
  private Long panelist_attr_122;
  private Long panelist_attr_123;
  private Long panelist_attr_124;
  private Long panelist_attr_125;
  private Long panelist_attr_126;
  private Long panelist_attr_127;
  private Long panelist_attr_128;
  private Long panelist_attr_129;
  private Long panelist_attr_130;
  private Long panelist_attr_131;
  private Long panelist_attr_132;
  private Long panelist_attr_133;
  private Long panelist_attr_134;
  private Long panelist_attr_135;
  private Long panelist_attr_136;
  private Long panelist_attr_137;
  private Long panelist_attr_138;
  private Long panelist_attr_139;
  private Long panelist_attr_140;
  private Long panelist_attr_141;
  private Long panelist_attr_142;
  private Long panelist_attr_143;
  private Long panelist_attr_144;
  private Long panelist_attr_145;
  private Long panelist_attr_146;
  private Long panelist_attr_147;
  private Long panelist_attr_148;
  private Long panelist_attr_149;
  private Long panelist_attr_150;
  private Long panelist_attr_151;
  private Long panelist_attr_152;
  private Long panelist_attr_153;
  private Long panelist_attr_154;
  private Long panelist_attr_155;
  private Long panelist_attr_156;
  private Long panelist_attr_157;
  private Long panelist_attr_158;
  private Long panelist_attr_159;
  private String questionnaire_values_04;
  private java.util.List<java.lang.Long> sdr_primary_key;
  private String end_of_rec;
        public String getCountry() {
                return this.country;
        }

        public void setCountry(String country) {
                this.country = country;
        }

        public String getBusiness() {
                return this.business;
        }

        public void setBusiness(String business) {
                this.business = business;
        }

        public String getData_source() {
                return this.data_source;
        }

        public void setData_source(String data_source) {
                this.data_source = data_source;
        }

        public String getData_frequency() {
                return this.data_frequency;
        }

        public void setData_frequency(String data_frequency) {
                this.data_frequency = data_frequency;
        }

        public Long getDml_version() {
                return this.dml_version;
        }

        public void setDml_version(Long dml_version) {
                this.dml_version = dml_version;
        }

        public Long getPanelist_seqno() {
                return this.panelist_seqno;
        }

        public void setPanelist_seqno(Long panelist_seqno) {
                this.panelist_seqno = panelist_seqno;
        }

        public Long getBre_version() {
                return this.bre_version;
        }

        public void setBre_version(Long bre_version) {
                this.bre_version = bre_version;
        }

        public Long getData_year() {
                return this.data_year;
        }

        public void setData_year(Long data_year) {
                this.data_year = data_year;
        }

        public Long getData_month() {
                return this.data_month;
        }

        public void setData_month(Long data_month) {
                this.data_month = data_month;
        }

        public Long getData_week() {
                return this.data_week;
        }

        public void setData_week(Long data_week) {
                this.data_week = data_week;
        }

        public Long getData_week_number() {
                return this.data_week_number;
        }

        public void setData_week_number(Long data_week_number) {
                this.data_week_number = data_week_number;
        }

        public Long getData_day() {
                return this.data_day;
        }

        public void setData_day(Long data_day) {
                this.data_day = data_day;
        }

        public Long getPpmonth() {
                return this.ppmonth;
        }

        public void setPpmonth(Long ppmonth) {
                this.ppmonth = ppmonth;
        }

        public Long getPpweek() {
                return this.ppweek;
        }

        public void setPpweek(Long ppweek) {
                this.ppweek = ppweek;
        }

        public String getAdded_date() {
                return this.added_date;
        }

        public void setAdded_date(String added_date) {
                this.added_date = added_date;
        }

        public String getUpdated_date() {
                return this.updated_date;
        }

        public void setUpdated_date(String updated_date) {
                this.updated_date = updated_date;
        }

        public Long getLoad_id() {
                return this.load_id;
        }

        public void setLoad_id(Long load_id) {
                this.load_id = load_id;
        }

        public java.util.List<java.lang.Long> getPrimary_key() {
                return this.primary_key;
        }

        public void setPrimary_key(java.util.List<java.lang.Long> primary_key) {
                this.primary_key = primary_key;
        }

        public Long getPanelist_id() {
                return this.panelist_id;
        }

        public void setPanelist_id(Long panelist_id) {
                this.panelist_id = panelist_id;
        }

        public String getProjection_date() {
                return this.projection_date;
        }

        public void setProjection_date(String projection_date) {
                this.projection_date = projection_date;
        }

        public String getSurvey_start_date() {
                return this.survey_start_date;
        }

        public void setSurvey_start_date(String survey_start_date) {
                this.survey_start_date = survey_start_date;
        }

        public Long getHousehold_head() {
                return this.household_head;
        }

        public void setHousehold_head(Long household_head) {
                this.household_head = household_head;
        }

        public Long getAge() {
                return this.age;
        }

        public void setAge(Long age) {
                this.age = age;
        }

        public Long getMale_head_age() {
                return this.male_head_age;
        }

        public void setMale_head_age(Long male_head_age) {
                this.male_head_age = male_head_age;
        }

        public Long getFemale_head_age() {
                return this.female_head_age;
        }

        public void setFemale_head_age(Long female_head_age) {
                this.female_head_age = female_head_age;
        }

        public Long getHead_of_household_age() {
                return this.head_of_household_age;
        }

        public void setHead_of_household_age(Long head_of_household_age) {
                this.head_of_household_age = head_of_household_age;
        }

        public Long getSurvey_age() {
                return this.survey_age;
        }

        public void setSurvey_age(Long survey_age) {
                this.survey_age = survey_age;
        }

        public Long getGender() {
                return this.gender;
        }

        public void setGender(Long gender) {
                this.gender = gender;
        }

        public Long getSurvey_gender() {
                return this.survey_gender;
        }

        public void setSurvey_gender(Long survey_gender) {
                this.survey_gender = survey_gender;
        }

        public Long getRace() {
                return this.race;
        }

        public void setRace(Long race) {
                this.race = race;
        }

        public Long getHispanic() {
                return this.hispanic;
        }

        public void setHispanic(Long hispanic) {
                this.hispanic = hispanic;
        }

        public Long getEthnic_group() {
                return this.ethnic_group;
        }

        public void setEthnic_group(Long ethnic_group) {
                this.ethnic_group = ethnic_group;
        }

        public Long getMarital_status() {
                return this.marital_status;
        }

        public void setMarital_status(Long marital_status) {
                this.marital_status = marital_status;
        }

        public Long getEducation() {
                return this.education;
        }

        public void setEducation(Long education) {
                this.education = education;
        }

        public Long getEducation_detail() {
                return this.education_detail;
        }

        public void setEducation_detail(Long education_detail) {
                this.education_detail = education_detail;
        }

        public Long getEmployment() {
                return this.employment;
        }

        public void setEmployment(Long employment) {
                this.employment = employment;
        }

        public Long getMale_head_employment() {
                return this.male_head_employment;
        }

        public void setMale_head_employment(Long male_head_employment) {
                this.male_head_employment = male_head_employment;
        }

        public Long getFemale_head_employment() {
                return this.female_head_employment;
        }

        public void setFemale_head_employment(Long female_head_employment) {
                this.female_head_employment = female_head_employment;
        }

        public Long getEmployment_status() {
                return this.employment_status;
        }

        public void setEmployment_status(Long employment_status) {
                this.employment_status = employment_status;
        }

        public Long getOccupation() {
                return this.occupation;
        }

        public void setOccupation(Long occupation) {
                this.occupation = occupation;
        }

        public Long getMale_head_occupation() {
                return this.male_head_occupation;
        }

        public void setMale_head_occupation(Long male_head_occupation) {
                this.male_head_occupation = male_head_occupation;
        }

        public Long getFemale_head_occupation() {
                return this.female_head_occupation;
        }

        public void setFemale_head_occupation(Long female_head_occupation) {
                this.female_head_occupation = female_head_occupation;
        }

        public Long getMale_head_education() {
                return this.male_head_education;
        }

        public void setMale_head_education(Long male_head_education) {
                this.male_head_education = male_head_education;
        }

        public Long getFemale_head_education() {
                return this.female_head_education;
        }

        public void setFemale_head_education(Long female_head_education) {
                this.female_head_education = female_head_education;
        }

        public Long getBuyer() {
                return this.buyer;
        }

        public void setBuyer(Long buyer) {
                this.buyer = buyer;
        }

        public Long getHousehold_income() {
                return this.household_income;
        }

        public void setHousehold_income(Long household_income) {
                this.household_income = household_income;
        }

        public Long getHousehold_size() {
                return this.household_size;
        }

        public void setHousehold_size(Long household_size) {
                this.household_size = household_size;
        }

        public Long getHousehold_composition() {
                return this.household_composition;
        }

        public void setHousehold_composition(Long household_composition) {
                this.household_composition = household_composition;
        }

        public Long getAge_of_children() {
                return this.age_of_children;
        }

        public void setAge_of_children(Long age_of_children) {
                this.age_of_children = age_of_children;
        }

        public Long getLife_cycle() {
                return this.life_cycle;
        }

        public void setLife_cycle(Long life_cycle) {
                this.life_cycle = life_cycle;
        }

        public Long getMicrovision() {
                return this.microvision;
        }

        public void setMicrovision(Long microvision) {
                this.microvision = microvision;
        }

        public Long getPrism() {
                return this.prism;
        }

        public void setPrism(Long prism) {
                this.prism = prism;
        }

        public Long getSpectra() {
                return this.spectra;
        }

        public void setSpectra(Long spectra) {
                this.spectra = spectra;
        }

        public Long getMarket_size() {
                return this.market_size;
        }

        public void setMarket_size(Long market_size) {
                this.market_size = market_size;
        }

        public Long getCbsa_market_size() {
                return this.cbsa_market_size;
        }

        public void setCbsa_market_size(Long cbsa_market_size) {
                this.cbsa_market_size = cbsa_market_size;
        }

        public Long getPg_market_size() {
                return this.pg_market_size;
        }

        public void setPg_market_size(Long pg_market_size) {
                this.pg_market_size = pg_market_size;
        }

        public Long getState() {
                return this.state;
        }

        public void setState(Long state) {
                this.state = state;
        }

        public Long getDma() {
                return this.dma;
        }

        public void setDma(Long dma) {
                this.dma = dma;
        }

        public Long getMsa() {
                return this.msa;
        }

        public void setMsa(Long msa) {
                this.msa = msa;
        }

        public String getPostal_code() {
                return this.postal_code;
        }

        public void setPostal_code(String postal_code) {
                this.postal_code = postal_code;
        }

        public Long getGroup_number() {
                return this.group_number;
        }

        public void setGroup_number(Long group_number) {
                this.group_number = group_number;
        }

        public Long getNumber_of_trackers() {
                return this.number_of_trackers;
        }

        public void setNumber_of_trackers(Long number_of_trackers) {
                this.number_of_trackers = number_of_trackers;
        }

        public Long getNumber_of_trackers_6mos() {
                return this.number_of_trackers_6mos;
        }

        public void setNumber_of_trackers_6mos(Long number_of_trackers_6mos) {
                this.number_of_trackers_6mos = number_of_trackers_6mos;
        }

        public Long getDays_on_panel() {
                return this.days_on_panel;
        }

        public void setDays_on_panel(Long days_on_panel) {
                this.days_on_panel = days_on_panel;
        }

        public Long getActive_days_on_panel() {
                return this.active_days_on_panel;
        }

        public void setActive_days_on_panel(Long active_days_on_panel) {
                this.active_days_on_panel = active_days_on_panel;
        }

        public Long getMonths_on_panel() {
                return this.months_on_panel;
        }

        public void setMonths_on_panel(Long months_on_panel) {
                this.months_on_panel = months_on_panel;
        }

        public Long getQuality_score() {
                return this.quality_score;
        }

        public void setQuality_score(Long quality_score) {
                this.quality_score = quality_score;
        }

        public Long getSamsclub_segmentation() {
                return this.samsclub_segmentation;
        }

        public void setSamsclub_segmentation(Long samsclub_segmentation) {
                this.samsclub_segmentation = samsclub_segmentation;
        }

        public Long getWalmart_segmentation() {
                return this.walmart_segmentation;
        }

        public void setWalmart_segmentation(Long walmart_segmentation) {
                this.walmart_segmentation = walmart_segmentation;
        }

        public Long getInternet_access() {
                return this.internet_access;
        }

        public void setInternet_access(Long internet_access) {
                this.internet_access = internet_access;
        }

        public Long getComputer_location() {
                return this.computer_location;
        }

        public void setComputer_location(Long computer_location) {
                this.computer_location = computer_location;
        }

        public Long getConnection_type() {
                return this.connection_type;
        }

        public void setConnection_type(Long connection_type) {
                this.connection_type = connection_type;
        }

        public Long getOperating_system() {
                return this.operating_system;
        }

        public void setOperating_system(Long operating_system) {
                this.operating_system = operating_system;
        }

        public Long getPc_type() {
                return this.pc_type;
        }

        public void setPc_type(Long pc_type) {
                this.pc_type = pc_type;
        }

        public Long getWork_at_home() {
                return this.work_at_home;
        }

        public void setWork_at_home(Long work_at_home) {
                this.work_at_home = work_at_home;
        }

        public Long getClosed_custom_counter() {
                return this.closed_custom_counter;
        }

        public void setClosed_custom_counter(Long closed_custom_counter) {
                this.closed_custom_counter = closed_custom_counter;
        }

        public Long getClosed_tracker_counter() {
                return this.closed_tracker_counter;
        }

        public void setClosed_tracker_counter(Long closed_tracker_counter) {
                this.closed_tracker_counter = closed_tracker_counter;
        }

        public Long getCnr_counter() {
                return this.cnr_counter;
        }

        public void setCnr_counter(Long cnr_counter) {
                this.cnr_counter = cnr_counter;
        }

        public Long getMega_reclaim_counter() {
                return this.mega_reclaim_counter;
        }

        public void setMega_reclaim_counter(Long mega_reclaim_counter) {
                this.mega_reclaim_counter = mega_reclaim_counter;
        }

        public Long getProh_reclaim_counter() {
                return this.proh_reclaim_counter;
        }

        public void setProh_reclaim_counter(Long proh_reclaim_counter) {
                this.proh_reclaim_counter = proh_reclaim_counter;
        }

        public Long getInactive_reclaim_counter() {
                return this.inactive_reclaim_counter;
        }

        public void setInactive_reclaim_counter(Long inactive_reclaim_counter) {
                this.inactive_reclaim_counter = inactive_reclaim_counter;
        }

        public Long getFactors__projection_factor() {
                return this.factors__projection_factor;
        }

        public void setFactors__projection_factor(Long factors__projection_factor) {
                this.factors__projection_factor = factors__projection_factor;
        }

        public Long getFactors__routing_factor() {
                return this.factors__routing_factor;
        }

        public void setFactors__routing_factor(Long factors__routing_factor) {
                this.factors__routing_factor = factors__routing_factor;
        }

        public Long getPanelist_attr_0() {
                return this.panelist_attr_0;
        }

        public void setPanelist_attr_0(Long panelist_attr_0) {
                this.panelist_attr_0 = panelist_attr_0;
        }

        public Long getPanelist_attr_1() {
                return this.panelist_attr_1;
        }

        public void setPanelist_attr_1(Long panelist_attr_1) {
                this.panelist_attr_1 = panelist_attr_1;
        }

        public Long getPanelist_attr_2() {
                return this.panelist_attr_2;
        }

        public void setPanelist_attr_2(Long panelist_attr_2) {
                this.panelist_attr_2 = panelist_attr_2;
        }

        public Long getPanelist_attr_3() {
                return this.panelist_attr_3;
        }

        public void setPanelist_attr_3(Long panelist_attr_3) {
                this.panelist_attr_3 = panelist_attr_3;
        }

        public Long getPanelist_attr_4() {
                return this.panelist_attr_4;
        }

        public void setPanelist_attr_4(Long panelist_attr_4) {
                this.panelist_attr_4 = panelist_attr_4;
        }

        public Long getPanelist_attr_5() {
                return this.panelist_attr_5;
        }

        public void setPanelist_attr_5(Long panelist_attr_5) {
                this.panelist_attr_5 = panelist_attr_5;
        }

        public Long getPanelist_attr_6() {
                return this.panelist_attr_6;
        }

        public void setPanelist_attr_6(Long panelist_attr_6) {
                this.panelist_attr_6 = panelist_attr_6;
        }

        public Long getPanelist_attr_7() {
                return this.panelist_attr_7;
        }

        public void setPanelist_attr_7(Long panelist_attr_7) {
                this.panelist_attr_7 = panelist_attr_7;
        }

        public Long getPanelist_attr_8() {
                return this.panelist_attr_8;
        }

        public void setPanelist_attr_8(Long panelist_attr_8) {
                this.panelist_attr_8 = panelist_attr_8;
        }

        public Long getPanelist_attr_9() {
                return this.panelist_attr_9;
        }

        public void setPanelist_attr_9(Long panelist_attr_9) {
                this.panelist_attr_9 = panelist_attr_9;
        }

        public Long getPanelist_attr_10() {
                return this.panelist_attr_10;
        }

        public void setPanelist_attr_10(Long panelist_attr_10) {
                this.panelist_attr_10 = panelist_attr_10;
        }

        public Long getPanelist_attr_11() {
                return this.panelist_attr_11;
        }

        public void setPanelist_attr_11(Long panelist_attr_11) {
                this.panelist_attr_11 = panelist_attr_11;
        }

        public Long getPanelist_attr_12() {
                return this.panelist_attr_12;
        }

        public void setPanelist_attr_12(Long panelist_attr_12) {
                this.panelist_attr_12 = panelist_attr_12;
        }

        public Long getPanelist_attr_13() {
                return this.panelist_attr_13;
        }

        public void setPanelist_attr_13(Long panelist_attr_13) {
                this.panelist_attr_13 = panelist_attr_13;
        }

        public Long getPanelist_attr_14() {
                return this.panelist_attr_14;
        }

        public void setPanelist_attr_14(Long panelist_attr_14) {
                this.panelist_attr_14 = panelist_attr_14;
        }

        public Long getPanelist_attr_15() {
                return this.panelist_attr_15;
        }

        public void setPanelist_attr_15(Long panelist_attr_15) {
                this.panelist_attr_15 = panelist_attr_15;
        }

        public Long getPanelist_attr_16() {
                return this.panelist_attr_16;
        }

        public void setPanelist_attr_16(Long panelist_attr_16) {
                this.panelist_attr_16 = panelist_attr_16;
        }

        public Long getPanelist_attr_17() {
                return this.panelist_attr_17;
        }

        public void setPanelist_attr_17(Long panelist_attr_17) {
                this.panelist_attr_17 = panelist_attr_17;
        }

        public Long getPanelist_attr_18() {
                return this.panelist_attr_18;
        }

        public void setPanelist_attr_18(Long panelist_attr_18) {
                this.panelist_attr_18 = panelist_attr_18;
        }

        public Long getPanelist_attr_19() {
                return this.panelist_attr_19;
        }

        public void setPanelist_attr_19(Long panelist_attr_19) {
                this.panelist_attr_19 = panelist_attr_19;
        }

        public Long getPanelist_attr_20() {
                return this.panelist_attr_20;
        }

        public void setPanelist_attr_20(Long panelist_attr_20) {
                this.panelist_attr_20 = panelist_attr_20;
        }

        public Long getPanelist_attr_21() {
                return this.panelist_attr_21;
        }

        public void setPanelist_attr_21(Long panelist_attr_21) {
                this.panelist_attr_21 = panelist_attr_21;
        }

        public Long getPanelist_attr_22() {
                return this.panelist_attr_22;
        }

        public void setPanelist_attr_22(Long panelist_attr_22) {
                this.panelist_attr_22 = panelist_attr_22;
        }

        public Long getPanelist_attr_23() {
                return this.panelist_attr_23;
        }

        public void setPanelist_attr_23(Long panelist_attr_23) {
                this.panelist_attr_23 = panelist_attr_23;
        }

        public Long getPanelist_attr_24() {
                return this.panelist_attr_24;
        }

        public void setPanelist_attr_24(Long panelist_attr_24) {
                this.panelist_attr_24 = panelist_attr_24;
        }

        public Long getPanelist_attr_25() {
                return this.panelist_attr_25;
        }

        public void setPanelist_attr_25(Long panelist_attr_25) {
                this.panelist_attr_25 = panelist_attr_25;
        }

        public Long getPanelist_attr_26() {
                return this.panelist_attr_26;
        }

        public void setPanelist_attr_26(Long panelist_attr_26) {
                this.panelist_attr_26 = panelist_attr_26;
        }

        public Long getPanelist_attr_27() {
                return this.panelist_attr_27;
        }

        public void setPanelist_attr_27(Long panelist_attr_27) {
                this.panelist_attr_27 = panelist_attr_27;
        }

        public Long getPanelist_attr_28() {
                return this.panelist_attr_28;
        }

        public void setPanelist_attr_28(Long panelist_attr_28) {
                this.panelist_attr_28 = panelist_attr_28;
        }

        public Long getPanelist_attr_29() {
                return this.panelist_attr_29;
        }

        public void setPanelist_attr_29(Long panelist_attr_29) {
                this.panelist_attr_29 = panelist_attr_29;
        }

        public Long getPanelist_attr_30() {
                return this.panelist_attr_30;
        }

        public void setPanelist_attr_30(Long panelist_attr_30) {
                this.panelist_attr_30 = panelist_attr_30;
        }

        public Long getPanelist_attr_31() {
                return this.panelist_attr_31;
        }

        public void setPanelist_attr_31(Long panelist_attr_31) {
                this.panelist_attr_31 = panelist_attr_31;
        }

        public Long getPanelist_attr_32() {
                return this.panelist_attr_32;
        }

        public void setPanelist_attr_32(Long panelist_attr_32) {
                this.panelist_attr_32 = panelist_attr_32;
        }

        public Long getPanelist_attr_33() {
                return this.panelist_attr_33;
        }

        public void setPanelist_attr_33(Long panelist_attr_33) {
                this.panelist_attr_33 = panelist_attr_33;
        }

        public Long getPanelist_attr_34() {
                return this.panelist_attr_34;
        }

        public void setPanelist_attr_34(Long panelist_attr_34) {
                this.panelist_attr_34 = panelist_attr_34;
        }

        public Long getPanelist_attr_35() {
                return this.panelist_attr_35;
        }

        public void setPanelist_attr_35(Long panelist_attr_35) {
                this.panelist_attr_35 = panelist_attr_35;
        }

        public Long getPanelist_attr_36() {
                return this.panelist_attr_36;
        }

        public void setPanelist_attr_36(Long panelist_attr_36) {
                this.panelist_attr_36 = panelist_attr_36;
        }

        public Long getPanelist_attr_37() {
                return this.panelist_attr_37;
        }

        public void setPanelist_attr_37(Long panelist_attr_37) {
                this.panelist_attr_37 = panelist_attr_37;
        }

        public Long getPanelist_attr_38() {
                return this.panelist_attr_38;
        }

        public void setPanelist_attr_38(Long panelist_attr_38) {
                this.panelist_attr_38 = panelist_attr_38;
        }

        public Long getPanelist_attr_39() {
                return this.panelist_attr_39;
        }

        public void setPanelist_attr_39(Long panelist_attr_39) {
                this.panelist_attr_39 = panelist_attr_39;
        }

        public Long getPanelist_attr_40() {
                return this.panelist_attr_40;
        }

        public void setPanelist_attr_40(Long panelist_attr_40) {
                this.panelist_attr_40 = panelist_attr_40;
        }

        public Long getPanelist_attr_41() {
                return this.panelist_attr_41;
        }

        public void setPanelist_attr_41(Long panelist_attr_41) {
                this.panelist_attr_41 = panelist_attr_41;
        }

        public Long getPanelist_attr_42() {
                return this.panelist_attr_42;
        }

        public void setPanelist_attr_42(Long panelist_attr_42) {
                this.panelist_attr_42 = panelist_attr_42;
        }

        public Long getPanelist_attr_43() {
                return this.panelist_attr_43;
        }

        public void setPanelist_attr_43(Long panelist_attr_43) {
                this.panelist_attr_43 = panelist_attr_43;
        }

        public Long getPanelist_attr_44() {
                return this.panelist_attr_44;
        }

        public void setPanelist_attr_44(Long panelist_attr_44) {
                this.panelist_attr_44 = panelist_attr_44;
        }

        public Long getPanelist_attr_45() {
                return this.panelist_attr_45;
        }

        public void setPanelist_attr_45(Long panelist_attr_45) {
                this.panelist_attr_45 = panelist_attr_45;
        }

        public Long getPanelist_attr_46() {
                return this.panelist_attr_46;
        }

        public void setPanelist_attr_46(Long panelist_attr_46) {
                this.panelist_attr_46 = panelist_attr_46;
        }

        public Long getPanelist_attr_47() {
                return this.panelist_attr_47;
        }

        public void setPanelist_attr_47(Long panelist_attr_47) {
                this.panelist_attr_47 = panelist_attr_47;
        }

        public Long getPanelist_attr_48() {
                return this.panelist_attr_48;
        }

        public void setPanelist_attr_48(Long panelist_attr_48) {
                this.panelist_attr_48 = panelist_attr_48;
        }

        public Long getPanelist_attr_49() {
                return this.panelist_attr_49;
        }

        public void setPanelist_attr_49(Long panelist_attr_49) {
                this.panelist_attr_49 = panelist_attr_49;
        }

        public Long getPanelist_attr_50() {
                return this.panelist_attr_50;
        }

        public void setPanelist_attr_50(Long panelist_attr_50) {
                this.panelist_attr_50 = panelist_attr_50;
        }

        public Long getPanelist_attr_51() {
                return this.panelist_attr_51;
        }

        public void setPanelist_attr_51(Long panelist_attr_51) {
                this.panelist_attr_51 = panelist_attr_51;
        }

        public Long getPanelist_attr_52() {
                return this.panelist_attr_52;
        }

        public void setPanelist_attr_52(Long panelist_attr_52) {
                this.panelist_attr_52 = panelist_attr_52;
        }

        public Long getPanelist_attr_53() {
                return this.panelist_attr_53;
        }

        public void setPanelist_attr_53(Long panelist_attr_53) {
                this.panelist_attr_53 = panelist_attr_53;
        }

        public Long getPanelist_attr_54() {
                return this.panelist_attr_54;
        }

        public void setPanelist_attr_54(Long panelist_attr_54) {
                this.panelist_attr_54 = panelist_attr_54;
        }

        public Long getPanelist_attr_55() {
                return this.panelist_attr_55;
        }

        public void setPanelist_attr_55(Long panelist_attr_55) {
                this.panelist_attr_55 = panelist_attr_55;
        }

        public Long getPanelist_attr_56() {
                return this.panelist_attr_56;
        }

        public void setPanelist_attr_56(Long panelist_attr_56) {
                this.panelist_attr_56 = panelist_attr_56;
        }

        public Long getPanelist_attr_57() {
                return this.panelist_attr_57;
        }

        public void setPanelist_attr_57(Long panelist_attr_57) {
                this.panelist_attr_57 = panelist_attr_57;
        }

        public Long getPanelist_attr_58() {
                return this.panelist_attr_58;
        }

        public void setPanelist_attr_58(Long panelist_attr_58) {
                this.panelist_attr_58 = panelist_attr_58;
        }

        public Long getPanelist_attr_59() {
                return this.panelist_attr_59;
        }

        public void setPanelist_attr_59(Long panelist_attr_59) {
                this.panelist_attr_59 = panelist_attr_59;
        }

        public Long getPanelist_attr_60() {
                return this.panelist_attr_60;
        }

        public void setPanelist_attr_60(Long panelist_attr_60) {
                this.panelist_attr_60 = panelist_attr_60;
        }

        public Long getPanelist_attr_61() {
                return this.panelist_attr_61;
        }

        public void setPanelist_attr_61(Long panelist_attr_61) {
                this.panelist_attr_61 = panelist_attr_61;
        }

        public Long getPanelist_attr_62() {
                return this.panelist_attr_62;
        }

        public void setPanelist_attr_62(Long panelist_attr_62) {
                this.panelist_attr_62 = panelist_attr_62;
        }

        public Long getPanelist_attr_63() {
                return this.panelist_attr_63;
        }

        public void setPanelist_attr_63(Long panelist_attr_63) {
                this.panelist_attr_63 = panelist_attr_63;
        }

        public Long getPanelist_attr_64() {
                return this.panelist_attr_64;
        }

        public void setPanelist_attr_64(Long panelist_attr_64) {
                this.panelist_attr_64 = panelist_attr_64;
        }

        public Long getPanelist_attr_65() {
                return this.panelist_attr_65;
        }

        public void setPanelist_attr_65(Long panelist_attr_65) {
                this.panelist_attr_65 = panelist_attr_65;
        }

        public Long getPanelist_attr_66() {
                return this.panelist_attr_66;
        }

        public void setPanelist_attr_66(Long panelist_attr_66) {
                this.panelist_attr_66 = panelist_attr_66;
        }

        public Long getPanelist_attr_67() {
                return this.panelist_attr_67;
        }

        public void setPanelist_attr_67(Long panelist_attr_67) {
                this.panelist_attr_67 = panelist_attr_67;
        }

        public Long getPanelist_attr_68() {
                return this.panelist_attr_68;
        }

        public void setPanelist_attr_68(Long panelist_attr_68) {
                this.panelist_attr_68 = panelist_attr_68;
        }

        public Long getPanelist_attr_69() {
                return this.panelist_attr_69;
        }

        public void setPanelist_attr_69(Long panelist_attr_69) {
                this.panelist_attr_69 = panelist_attr_69;
        }

        public Long getPanelist_attr_70() {
                return this.panelist_attr_70;
        }

        public void setPanelist_attr_70(Long panelist_attr_70) {
                this.panelist_attr_70 = panelist_attr_70;
        }

        public Long getPanelist_attr_71() {
                return this.panelist_attr_71;
        }

        public void setPanelist_attr_71(Long panelist_attr_71) {
                this.panelist_attr_71 = panelist_attr_71;
        }

        public Long getPanelist_attr_72() {
                return this.panelist_attr_72;
        }

        public void setPanelist_attr_72(Long panelist_attr_72) {
                this.panelist_attr_72 = panelist_attr_72;
        }

        public Long getPanelist_attr_73() {
                return this.panelist_attr_73;
        }

        public void setPanelist_attr_73(Long panelist_attr_73) {
                this.panelist_attr_73 = panelist_attr_73;
        }

        public Long getPanelist_attr_74() {
                return this.panelist_attr_74;
        }

        public void setPanelist_attr_74(Long panelist_attr_74) {
                this.panelist_attr_74 = panelist_attr_74;
        }

        public Long getPanelist_attr_75() {
                return this.panelist_attr_75;
        }

        public void setPanelist_attr_75(Long panelist_attr_75) {
                this.panelist_attr_75 = panelist_attr_75;
        }

        public Long getPanelist_attr_76() {
                return this.panelist_attr_76;
        }

        public void setPanelist_attr_76(Long panelist_attr_76) {
                this.panelist_attr_76 = panelist_attr_76;
        }

        public Long getPanelist_attr_77() {
                return this.panelist_attr_77;
        }

        public void setPanelist_attr_77(Long panelist_attr_77) {
                this.panelist_attr_77 = panelist_attr_77;
        }

        public Long getPanelist_attr_78() {
                return this.panelist_attr_78;
        }

        public void setPanelist_attr_78(Long panelist_attr_78) {
                this.panelist_attr_78 = panelist_attr_78;
        }

        public Long getPanelist_attr_79() {
                return this.panelist_attr_79;
        }

        public void setPanelist_attr_79(Long panelist_attr_79) {
                this.panelist_attr_79 = panelist_attr_79;
        }

        public Long getPanelist_attr_80() {
                return this.panelist_attr_80;
        }

        public void setPanelist_attr_80(Long panelist_attr_80) {
                this.panelist_attr_80 = panelist_attr_80;
        }

        public Long getPanelist_attr_81() {
                return this.panelist_attr_81;
        }

        public void setPanelist_attr_81(Long panelist_attr_81) {
                this.panelist_attr_81 = panelist_attr_81;
        }

        public Long getPanelist_attr_82() {
                return this.panelist_attr_82;
        }

        public void setPanelist_attr_82(Long panelist_attr_82) {
                this.panelist_attr_82 = panelist_attr_82;
        }

        public Long getPanelist_attr_83() {
                return this.panelist_attr_83;
        }

        public void setPanelist_attr_83(Long panelist_attr_83) {
                this.panelist_attr_83 = panelist_attr_83;
        }

        public Long getPanelist_attr_84() {
                return this.panelist_attr_84;
        }

        public void setPanelist_attr_84(Long panelist_attr_84) {
                this.panelist_attr_84 = panelist_attr_84;
        }

        public Long getPanelist_attr_85() {
                return this.panelist_attr_85;
        }

        public void setPanelist_attr_85(Long panelist_attr_85) {
                this.panelist_attr_85 = panelist_attr_85;
        }

        public Long getPanelist_attr_86() {
                return this.panelist_attr_86;
        }

        public void setPanelist_attr_86(Long panelist_attr_86) {
                this.panelist_attr_86 = panelist_attr_86;
        }

        public Long getPanelist_attr_87() {
                return this.panelist_attr_87;
        }

        public void setPanelist_attr_87(Long panelist_attr_87) {
                this.panelist_attr_87 = panelist_attr_87;
        }

        public Long getPanelist_attr_88() {
                return this.panelist_attr_88;
        }

        public void setPanelist_attr_88(Long panelist_attr_88) {
                this.panelist_attr_88 = panelist_attr_88;
        }

        public Long getPanelist_attr_89() {
                return this.panelist_attr_89;
        }

        public void setPanelist_attr_89(Long panelist_attr_89) {
                this.panelist_attr_89 = panelist_attr_89;
        }

        public Long getPanelist_attr_90() {
                return this.panelist_attr_90;
        }

        public void setPanelist_attr_90(Long panelist_attr_90) {
                this.panelist_attr_90 = panelist_attr_90;
        }

        public Long getPanelist_attr_91() {
                return this.panelist_attr_91;
        }

        public void setPanelist_attr_91(Long panelist_attr_91) {
                this.panelist_attr_91 = panelist_attr_91;
        }

        public Long getPanelist_attr_92() {
                return this.panelist_attr_92;
        }

        public void setPanelist_attr_92(Long panelist_attr_92) {
                this.panelist_attr_92 = panelist_attr_92;
        }

        public Long getPanelist_attr_93() {
                return this.panelist_attr_93;
        }

        public void setPanelist_attr_93(Long panelist_attr_93) {
                this.panelist_attr_93 = panelist_attr_93;
        }

        public Long getPanelist_attr_94() {
                return this.panelist_attr_94;
        }

        public void setPanelist_attr_94(Long panelist_attr_94) {
                this.panelist_attr_94 = panelist_attr_94;
        }

        public Long getPanelist_attr_95() {
                return this.panelist_attr_95;
        }

        public void setPanelist_attr_95(Long panelist_attr_95) {
                this.panelist_attr_95 = panelist_attr_95;
        }

        public Long getPanelist_attr_96() {
                return this.panelist_attr_96;
        }

        public void setPanelist_attr_96(Long panelist_attr_96) {
                this.panelist_attr_96 = panelist_attr_96;
        }

        public Long getPanelist_attr_97() {
                return this.panelist_attr_97;
        }

        public void setPanelist_attr_97(Long panelist_attr_97) {
                this.panelist_attr_97 = panelist_attr_97;
        }

        public Long getPanelist_attr_98() {
                return this.panelist_attr_98;
        }

        public void setPanelist_attr_98(Long panelist_attr_98) {
                this.panelist_attr_98 = panelist_attr_98;
        }

        public Long getPanelist_attr_99() {
                return this.panelist_attr_99;
        }

        public void setPanelist_attr_99(Long panelist_attr_99) {
                this.panelist_attr_99 = panelist_attr_99;
        }

        public java.util.List<java.lang.Long> getMulti_choice_codes_01() {
                return this.multi_choice_codes_01;
        }

        public void setMulti_choice_codes_01(java.util.List<java.lang.Long> multi_choice_codes_01) {
                this.multi_choice_codes_01 = multi_choice_codes_01;
        }

        public java.util.List<java.lang.Long> getMulti_choice_codes_02() {
                return this.multi_choice_codes_02;
        }

        public void setMulti_choice_codes_02(java.util.List<java.lang.Long> multi_choice_codes_02) {
                this.multi_choice_codes_02 = multi_choice_codes_02;
        }

        public java.util.List<java.lang.Long> getMulti_choice_codes_03() {
                return this.multi_choice_codes_03;
        }

        public void setMulti_choice_codes_03(java.util.List<java.lang.Long> multi_choice_codes_03) {
                this.multi_choice_codes_03 = multi_choice_codes_03;
        }

        public java.util.List<java.lang.Long> getMulti_choice_codes_04() {
                return this.multi_choice_codes_04;
        }

        public void setMulti_choice_codes_04(java.util.List<java.lang.Long> multi_choice_codes_04) {
                this.multi_choice_codes_04 = multi_choice_codes_04;
        }

        public java.util.List<java.lang.Long> getMulti_choice_codes_05() {
                return this.multi_choice_codes_05;
        }

        public void setMulti_choice_codes_05(java.util.List<java.lang.Long> multi_choice_codes_05) {
                this.multi_choice_codes_05 = multi_choice_codes_05;
        }

        public java.util.List<java.lang.Long> getMulti_choice_codes_06() {
                return this.multi_choice_codes_06;
        }

        public void setMulti_choice_codes_06(java.util.List<java.lang.Long> multi_choice_codes_06) {
                this.multi_choice_codes_06 = multi_choice_codes_06;
        }

        public java.util.List<java.lang.Long> getMulti_choice_codes_07() {
                return this.multi_choice_codes_07;
        }

        public void setMulti_choice_codes_07(java.util.List<java.lang.Long> multi_choice_codes_07) {
                this.multi_choice_codes_07 = multi_choice_codes_07;
        }

        public java.util.List<java.lang.Long> getMulti_choice_codes_08() {
                return this.multi_choice_codes_08;
        }

        public void setMulti_choice_codes_08(java.util.List<java.lang.Long> multi_choice_codes_08) {
                this.multi_choice_codes_08 = multi_choice_codes_08;
        }

        public java.util.List<java.lang.Long> getMulti_choice_codes_09() {
                return this.multi_choice_codes_09;
        }

        public void setMulti_choice_codes_09(java.util.List<java.lang.Long> multi_choice_codes_09) {
                this.multi_choice_codes_09 = multi_choice_codes_09;
        }

        public java.util.List<java.lang.Long> getMulti_choice_codes_10() {
                return this.multi_choice_codes_10;
        }

        public void setMulti_choice_codes_10(java.util.List<java.lang.Long> multi_choice_codes_10) {
                this.multi_choice_codes_10 = multi_choice_codes_10;
        }

        public java.util.List<java.lang.Long> getMulti_choice_codes_11() {
                return this.multi_choice_codes_11;
        }

        public void setMulti_choice_codes_11(java.util.List<java.lang.Long> multi_choice_codes_11) {
                this.multi_choice_codes_11 = multi_choice_codes_11;
        }

        public java.util.List<java.lang.Long> getMulti_choice_codes_12() {
                return this.multi_choice_codes_12;
        }

        public void setMulti_choice_codes_12(java.util.List<java.lang.Long> multi_choice_codes_12) {
                this.multi_choice_codes_12 = multi_choice_codes_12;
        }

        public java.util.List<java.lang.Long> getMulti_choice_codes_13() {
                return this.multi_choice_codes_13;
        }

        public void setMulti_choice_codes_13(java.util.List<java.lang.Long> multi_choice_codes_13) {
                this.multi_choice_codes_13 = multi_choice_codes_13;
        }

        public java.util.List<java.lang.Long> getMulti_choice_codes_14() {
                return this.multi_choice_codes_14;
        }

        public void setMulti_choice_codes_14(java.util.List<java.lang.Long> multi_choice_codes_14) {
                this.multi_choice_codes_14 = multi_choice_codes_14;
        }

        public java.util.List<java.lang.Long> getMulti_choice_codes_15() {
                return this.multi_choice_codes_15;
        }

        public void setMulti_choice_codes_15(java.util.List<java.lang.Long> multi_choice_codes_15) {
                this.multi_choice_codes_15 = multi_choice_codes_15;
        }

        public java.util.List<java.lang.Long> getMulti_choice_codes_16() {
                return this.multi_choice_codes_16;
        }

        public void setMulti_choice_codes_16(java.util.List<java.lang.Long> multi_choice_codes_16) {
                this.multi_choice_codes_16 = multi_choice_codes_16;
        }

        public java.util.List<java.lang.Long> getMulti_choice_codes_17() {
                return this.multi_choice_codes_17;
        }

        public void setMulti_choice_codes_17(java.util.List<java.lang.Long> multi_choice_codes_17) {
                this.multi_choice_codes_17 = multi_choice_codes_17;
        }

        public java.util.List<java.lang.Long> getMulti_choice_codes_18() {
                return this.multi_choice_codes_18;
        }

        public void setMulti_choice_codes_18(java.util.List<java.lang.Long> multi_choice_codes_18) {
                this.multi_choice_codes_18 = multi_choice_codes_18;
        }

        public java.util.List<java.lang.Long> getMulti_choice_codes_19() {
                return this.multi_choice_codes_19;
        }

        public void setMulti_choice_codes_19(java.util.List<java.lang.Long> multi_choice_codes_19) {
                this.multi_choice_codes_19 = multi_choice_codes_19;
        }

        public java.util.List<java.lang.Long> getMulti_choice_codes_20() {
                return this.multi_choice_codes_20;
        }

        public void setMulti_choice_codes_20(java.util.List<java.lang.Long> multi_choice_codes_20) {
                this.multi_choice_codes_20 = multi_choice_codes_20;
        }

        public java.util.List<java.lang.Long> getMulti_choice_codes_21() {
                return this.multi_choice_codes_21;
        }

        public void setMulti_choice_codes_21(java.util.List<java.lang.Long> multi_choice_codes_21) {
                this.multi_choice_codes_21 = multi_choice_codes_21;
        }

        public java.util.List<java.lang.Long> getMulti_choice_codes_22() {
                return this.multi_choice_codes_22;
        }

        public void setMulti_choice_codes_22(java.util.List<java.lang.Long> multi_choice_codes_22) {
                this.multi_choice_codes_22 = multi_choice_codes_22;
        }

        public java.util.List<java.lang.Long> getMulti_choice_codes_23() {
                return this.multi_choice_codes_23;
        }

        public void setMulti_choice_codes_23(java.util.List<java.lang.Long> multi_choice_codes_23) {
                this.multi_choice_codes_23 = multi_choice_codes_23;
        }

        public java.util.List<java.lang.Long> getMulti_choice_codes_24() {
                return this.multi_choice_codes_24;
        }

        public void setMulti_choice_codes_24(java.util.List<java.lang.Long> multi_choice_codes_24) {
                this.multi_choice_codes_24 = multi_choice_codes_24;
        }

        public java.util.List<java.lang.Long> getMulti_choice_codes_25() {
                return this.multi_choice_codes_25;
        }

        public void setMulti_choice_codes_25(java.util.List<java.lang.Long> multi_choice_codes_25) {
                this.multi_choice_codes_25 = multi_choice_codes_25;
        }

        public String getQuestionnaire_values_01() {
                return this.questionnaire_values_01;
        }

        public void setQuestionnaire_values_01(String questionnaire_values_01) {
                this.questionnaire_values_01 = questionnaire_values_01;
        }

        public String getQuestionnaire_values_02() {
                return this.questionnaire_values_02;
        }

        public void setQuestionnaire_values_02(String questionnaire_values_02) {
                this.questionnaire_values_02 = questionnaire_values_02;
        }

        public String getQuestionnaire_values_03() {
                return this.questionnaire_values_03;
        }

        public void setQuestionnaire_values_03(String questionnaire_values_03) {
                this.questionnaire_values_03 = questionnaire_values_03;
        }

        public String getReserved_fields__filler_1() {
                return this.reserved_fields__filler_1;
        }

        public void setReserved_fields__filler_1(String reserved_fields__filler_1) {
                this.reserved_fields__filler_1 = reserved_fields__filler_1;
        }

        public String getExtended_dml_flag() {
                return this.extended_dml_flag;
        }

        public void setExtended_dml_flag(String extended_dml_flag) {
                this.extended_dml_flag = extended_dml_flag;
        }

        public String getMail_date() {
                return this.mail_date;
        }

        public void setMail_date(String mail_date) {
                this.mail_date = mail_date;
        }

        public String getConfirmit_jobnum() {
                return this.confirmit_jobnum;
        }

        public void setConfirmit_jobnum(String confirmit_jobnum) {
                this.confirmit_jobnum = confirmit_jobnum;
        }

        public Long getEducation_dim__level_0() {
                return this.education_dim__level_0;
        }

        public void setEducation_dim__level_0(Long education_dim__level_0) {
                this.education_dim__level_0 = education_dim__level_0;
        }

        public Long getEducation_dim__level_1() {
                return this.education_dim__level_1;
        }

        public void setEducation_dim__level_1(Long education_dim__level_1) {
                this.education_dim__level_1 = education_dim__level_1;
        }

        public Long getEducation_dim__level_2() {
                return this.education_dim__level_2;
        }

        public void setEducation_dim__level_2(Long education_dim__level_2) {
                this.education_dim__level_2 = education_dim__level_2;
        }

        public Long getEducation_dim__level_3() {
                return this.education_dim__level_3;
        }

        public void setEducation_dim__level_3(Long education_dim__level_3) {
                this.education_dim__level_3 = education_dim__level_3;
        }

        public Long getEducation_dim__level_4() {
                return this.education_dim__level_4;
        }

        public void setEducation_dim__level_4(Long education_dim__level_4) {
                this.education_dim__level_4 = education_dim__level_4;
        }

        public Long getEducation_dim__level_5() {
                return this.education_dim__level_5;
        }

        public void setEducation_dim__level_5(Long education_dim__level_5) {
                this.education_dim__level_5 = education_dim__level_5;
        }

        public Long getEducation_dim__level_6() {
                return this.education_dim__level_6;
        }

        public void setEducation_dim__level_6(Long education_dim__level_6) {
                this.education_dim__level_6 = education_dim__level_6;
        }

        public Long getEducation_dim__level_7() {
                return this.education_dim__level_7;
        }

        public void setEducation_dim__level_7(Long education_dim__level_7) {
                this.education_dim__level_7 = education_dim__level_7;
        }

        public Long getEducation_dim__level_8() {
                return this.education_dim__level_8;
        }

        public void setEducation_dim__level_8(Long education_dim__level_8) {
                this.education_dim__level_8 = education_dim__level_8;
        }

        public Long getEducation_dim__level_9() {
                return this.education_dim__level_9;
        }

        public void setEducation_dim__level_9(Long education_dim__level_9) {
                this.education_dim__level_9 = education_dim__level_9;
        }

        public Long getGeo_dim__level_0() {
                return this.geo_dim__level_0;
        }

        public void setGeo_dim__level_0(Long geo_dim__level_0) {
                this.geo_dim__level_0 = geo_dim__level_0;
        }

        public Long getGeo_dim__level_1() {
                return this.geo_dim__level_1;
        }

        public void setGeo_dim__level_1(Long geo_dim__level_1) {
                this.geo_dim__level_1 = geo_dim__level_1;
        }

        public Long getGeo_dim__level_2() {
                return this.geo_dim__level_2;
        }

        public void setGeo_dim__level_2(Long geo_dim__level_2) {
                this.geo_dim__level_2 = geo_dim__level_2;
        }

        public Long getGeo_dim__level_3() {
                return this.geo_dim__level_3;
        }

        public void setGeo_dim__level_3(Long geo_dim__level_3) {
                this.geo_dim__level_3 = geo_dim__level_3;
        }

        public Long getGeo_dim__level_4() {
                return this.geo_dim__level_4;
        }

        public void setGeo_dim__level_4(Long geo_dim__level_4) {
                this.geo_dim__level_4 = geo_dim__level_4;
        }

        public Long getGeo_dim__level_5() {
                return this.geo_dim__level_5;
        }

        public void setGeo_dim__level_5(Long geo_dim__level_5) {
                this.geo_dim__level_5 = geo_dim__level_5;
        }

        public Long getGeo_dim__level_6() {
                return this.geo_dim__level_6;
        }

        public void setGeo_dim__level_6(Long geo_dim__level_6) {
                this.geo_dim__level_6 = geo_dim__level_6;
        }

        public Long getGeo_dim__level_7() {
                return this.geo_dim__level_7;
        }

        public void setGeo_dim__level_7(Long geo_dim__level_7) {
                this.geo_dim__level_7 = geo_dim__level_7;
        }

        public Long getGeo_dim__level_8() {
                return this.geo_dim__level_8;
        }

        public void setGeo_dim__level_8(Long geo_dim__level_8) {
                this.geo_dim__level_8 = geo_dim__level_8;
        }

        public Long getGeo_dim__level_9() {
                return this.geo_dim__level_9;
        }

        public void setGeo_dim__level_9(Long geo_dim__level_9) {
                this.geo_dim__level_9 = geo_dim__level_9;
        }

        public Long getHousehold_size_dim__level_0() {
                return this.household_size_dim__level_0;
        }

        public void setHousehold_size_dim__level_0(Long household_size_dim__level_0) {
                this.household_size_dim__level_0 = household_size_dim__level_0;
        }

        public Long getHousehold_size_dim__level_1() {
                return this.household_size_dim__level_1;
        }

        public void setHousehold_size_dim__level_1(Long household_size_dim__level_1) {
                this.household_size_dim__level_1 = household_size_dim__level_1;
        }

        public Long getHousehold_size_dim__level_2() {
                return this.household_size_dim__level_2;
        }

        public void setHousehold_size_dim__level_2(Long household_size_dim__level_2) {
                this.household_size_dim__level_2 = household_size_dim__level_2;
        }

        public Long getHousehold_size_dim__level_3() {
                return this.household_size_dim__level_3;
        }

        public void setHousehold_size_dim__level_3(Long household_size_dim__level_3) {
                this.household_size_dim__level_3 = household_size_dim__level_3;
        }

        public Long getHousehold_size_dim__level_4() {
                return this.household_size_dim__level_4;
        }

        public void setHousehold_size_dim__level_4(Long household_size_dim__level_4) {
                this.household_size_dim__level_4 = household_size_dim__level_4;
        }

        public Long getHousehold_size_dim__level_5() {
                return this.household_size_dim__level_5;
        }

        public void setHousehold_size_dim__level_5(Long household_size_dim__level_5) {
                this.household_size_dim__level_5 = household_size_dim__level_5;
        }

        public Long getHousehold_size_dim__level_6() {
                return this.household_size_dim__level_6;
        }

        public void setHousehold_size_dim__level_6(Long household_size_dim__level_6) {
                this.household_size_dim__level_6 = household_size_dim__level_6;
        }

        public Long getHousehold_size_dim__level_7() {
                return this.household_size_dim__level_7;
        }

        public void setHousehold_size_dim__level_7(Long household_size_dim__level_7) {
                this.household_size_dim__level_7 = household_size_dim__level_7;
        }

        public Long getHousehold_size_dim__level_8() {
                return this.household_size_dim__level_8;
        }

        public void setHousehold_size_dim__level_8(Long household_size_dim__level_8) {
                this.household_size_dim__level_8 = household_size_dim__level_8;
        }

        public Long getHousehold_size_dim__level_9() {
                return this.household_size_dim__level_9;
        }

        public void setHousehold_size_dim__level_9(Long household_size_dim__level_9) {
                this.household_size_dim__level_9 = household_size_dim__level_9;
        }

        public Long getHousehold_income_dim__level_0() {
                return this.household_income_dim__level_0;
        }

        public void setHousehold_income_dim__level_0(Long household_income_dim__level_0) {
                this.household_income_dim__level_0 = household_income_dim__level_0;
        }

        public Long getHousehold_income_dim__level_1() {
                return this.household_income_dim__level_1;
        }

        public void setHousehold_income_dim__level_1(Long household_income_dim__level_1) {
                this.household_income_dim__level_1 = household_income_dim__level_1;
        }

        public Long getHousehold_income_dim__level_2() {
                return this.household_income_dim__level_2;
        }

        public void setHousehold_income_dim__level_2(Long household_income_dim__level_2) {
                this.household_income_dim__level_2 = household_income_dim__level_2;
        }

        public Long getHousehold_income_dim__level_3() {
                return this.household_income_dim__level_3;
        }

        public void setHousehold_income_dim__level_3(Long household_income_dim__level_3) {
                this.household_income_dim__level_3 = household_income_dim__level_3;
        }

        public Long getHousehold_income_dim__level_4() {
                return this.household_income_dim__level_4;
        }

        public void setHousehold_income_dim__level_4(Long household_income_dim__level_4) {
                this.household_income_dim__level_4 = household_income_dim__level_4;
        }

        public Long getHousehold_income_dim__level_5() {
                return this.household_income_dim__level_5;
        }

        public void setHousehold_income_dim__level_5(Long household_income_dim__level_5) {
                this.household_income_dim__level_5 = household_income_dim__level_5;
        }

        public Long getHousehold_income_dim__level_6() {
                return this.household_income_dim__level_6;
        }

        public void setHousehold_income_dim__level_6(Long household_income_dim__level_6) {
                this.household_income_dim__level_6 = household_income_dim__level_6;
        }

        public Long getHousehold_income_dim__level_7() {
                return this.household_income_dim__level_7;
        }

        public void setHousehold_income_dim__level_7(Long household_income_dim__level_7) {
                this.household_income_dim__level_7 = household_income_dim__level_7;
        }

        public Long getHousehold_income_dim__level_8() {
                return this.household_income_dim__level_8;
        }

        public void setHousehold_income_dim__level_8(Long household_income_dim__level_8) {
                this.household_income_dim__level_8 = household_income_dim__level_8;
        }

        public Long getHousehold_income_dim__level_9() {
                return this.household_income_dim__level_9;
        }

        public void setHousehold_income_dim__level_9(Long household_income_dim__level_9) {
                this.household_income_dim__level_9 = household_income_dim__level_9;
        }

        public Long getComplete_flag() {
                return this.complete_flag;
        }

        public void setComplete_flag(Long complete_flag) {
                this.complete_flag = complete_flag;
        }

        public Long getStatus() {
                return this.status;
        }

        public void setStatus(Long status) {
                this.status = status;
        }

        public Long getFactor_values_0() {
                return this.factor_values_0;
        }

        public void setFactor_values_0(Long factor_values_0) {
                this.factor_values_0 = factor_values_0;
        }

        public Long getFactor_values_1() {
                return this.factor_values_1;
        }

        public void setFactor_values_1(Long factor_values_1) {
                this.factor_values_1 = factor_values_1;
        }

        public Long getFactor_values_2() {
                return this.factor_values_2;
        }

        public void setFactor_values_2(Long factor_values_2) {
                this.factor_values_2 = factor_values_2;
        }

        public Long getFactor_values_3() {
                return this.factor_values_3;
        }

        public void setFactor_values_3(Long factor_values_3) {
                this.factor_values_3 = factor_values_3;
        }

        public Long getFactor_values_4() {
                return this.factor_values_4;
        }

        public void setFactor_values_4(Long factor_values_4) {
                this.factor_values_4 = factor_values_4;
        }

        public Long getFactor_values_5() {
                return this.factor_values_5;
        }

        public void setFactor_values_5(Long factor_values_5) {
                this.factor_values_5 = factor_values_5;
        }

        public Long getFactor_values_6() {
                return this.factor_values_6;
        }

        public void setFactor_values_6(Long factor_values_6) {
                this.factor_values_6 = factor_values_6;
        }

        public Long getFactor_values_7() {
                return this.factor_values_7;
        }

        public void setFactor_values_7(Long factor_values_7) {
                this.factor_values_7 = factor_values_7;
        }

        public Long getFactor_values_8() {
                return this.factor_values_8;
        }

        public void setFactor_values_8(Long factor_values_8) {
                this.factor_values_8 = factor_values_8;
        }

        public Long getFactor_values_9() {
                return this.factor_values_9;
        }

        public void setFactor_values_9(Long factor_values_9) {
                this.factor_values_9 = factor_values_9;
        }

        public Long getFactor_values_10() {
                return this.factor_values_10;
        }

        public void setFactor_values_10(Long factor_values_10) {
                this.factor_values_10 = factor_values_10;
        }

        public Long getFactor_values_11() {
                return this.factor_values_11;
        }

        public void setFactor_values_11(Long factor_values_11) {
                this.factor_values_11 = factor_values_11;
        }

        public Long getFactor_values_12() {
                return this.factor_values_12;
        }

        public void setFactor_values_12(Long factor_values_12) {
                this.factor_values_12 = factor_values_12;
        }

        public Long getFactor_values_13() {
                return this.factor_values_13;
        }

        public void setFactor_values_13(Long factor_values_13) {
                this.factor_values_13 = factor_values_13;
        }

        public Long getFactor_values_14() {
                return this.factor_values_14;
        }

        public void setFactor_values_14(Long factor_values_14) {
                this.factor_values_14 = factor_values_14;
        }

        public Long getFactor_values_15() {
                return this.factor_values_15;
        }

        public void setFactor_values_15(Long factor_values_15) {
                this.factor_values_15 = factor_values_15;
        }

        public Long getFactor_values_16() {
                return this.factor_values_16;
        }

        public void setFactor_values_16(Long factor_values_16) {
                this.factor_values_16 = factor_values_16;
        }

        public Long getFactor_values_17() {
                return this.factor_values_17;
        }

        public void setFactor_values_17(Long factor_values_17) {
                this.factor_values_17 = factor_values_17;
        }

        public Long getFactor_values_18() {
                return this.factor_values_18;
        }

        public void setFactor_values_18(Long factor_values_18) {
                this.factor_values_18 = factor_values_18;
        }

        public Long getFactor_values_19() {
                return this.factor_values_19;
        }

        public void setFactor_values_19(Long factor_values_19) {
                this.factor_values_19 = factor_values_19;
        }

        public String getCns_raw_values_0() {
                return this.cns_raw_values_0;
        }

        public void setCns_raw_values_0(String cns_raw_values_0) {
                this.cns_raw_values_0 = cns_raw_values_0;
        }

        public String getCns_raw_values_1() {
                return this.cns_raw_values_1;
        }

        public void setCns_raw_values_1(String cns_raw_values_1) {
                this.cns_raw_values_1 = cns_raw_values_1;
        }

        public String getCns_raw_values_2() {
                return this.cns_raw_values_2;
        }

        public void setCns_raw_values_2(String cns_raw_values_2) {
                this.cns_raw_values_2 = cns_raw_values_2;
        }

        public String getCns_raw_values_3() {
                return this.cns_raw_values_3;
        }

        public void setCns_raw_values_3(String cns_raw_values_3) {
                this.cns_raw_values_3 = cns_raw_values_3;
        }

        public String getCns_raw_values_4() {
                return this.cns_raw_values_4;
        }

        public void setCns_raw_values_4(String cns_raw_values_4) {
                this.cns_raw_values_4 = cns_raw_values_4;
        }

        public java.util.List<java.lang.Long> getMulti_choice_codes_27() {
                return this.multi_choice_codes_27;
        }

        public void setMulti_choice_codes_27(java.util.List<java.lang.Long> multi_choice_codes_27) {
                this.multi_choice_codes_27 = multi_choice_codes_27;
        }

        public Long getPanelist_attr_100() {
                return this.panelist_attr_100;
        }

        public void setPanelist_attr_100(Long panelist_attr_100) {
                this.panelist_attr_100 = panelist_attr_100;
        }

        public Long getPanelist_attr_101() {
                return this.panelist_attr_101;
        }

        public void setPanelist_attr_101(Long panelist_attr_101) {
                this.panelist_attr_101 = panelist_attr_101;
        }

        public Long getPanelist_attr_102() {
                return this.panelist_attr_102;
        }

        public void setPanelist_attr_102(Long panelist_attr_102) {
                this.panelist_attr_102 = panelist_attr_102;
        }

        public Long getPanelist_attr_103() {
                return this.panelist_attr_103;
        }

        public void setPanelist_attr_103(Long panelist_attr_103) {
                this.panelist_attr_103 = panelist_attr_103;
        }

        public Long getPanelist_attr_104() {
                return this.panelist_attr_104;
        }

        public void setPanelist_attr_104(Long panelist_attr_104) {
                this.panelist_attr_104 = panelist_attr_104;
        }

        public Long getPanelist_attr_105() {
                return this.panelist_attr_105;
        }

        public void setPanelist_attr_105(Long panelist_attr_105) {
                this.panelist_attr_105 = panelist_attr_105;
        }

        public Long getPanelist_attr_106() {
                return this.panelist_attr_106;
        }

        public void setPanelist_attr_106(Long panelist_attr_106) {
                this.panelist_attr_106 = panelist_attr_106;
        }

        public Long getPanelist_attr_107() {
                return this.panelist_attr_107;
        }

        public void setPanelist_attr_107(Long panelist_attr_107) {
                this.panelist_attr_107 = panelist_attr_107;
        }

        public Long getPanelist_attr_108() {
                return this.panelist_attr_108;
        }

        public void setPanelist_attr_108(Long panelist_attr_108) {
                this.panelist_attr_108 = panelist_attr_108;
        }

        public Long getPanelist_attr_109() {
                return this.panelist_attr_109;
        }

        public void setPanelist_attr_109(Long panelist_attr_109) {
                this.panelist_attr_109 = panelist_attr_109;
        }

        public Long getPanelist_attr_110() {
                return this.panelist_attr_110;
        }

        public void setPanelist_attr_110(Long panelist_attr_110) {
                this.panelist_attr_110 = panelist_attr_110;
        }

        public Long getPanelist_attr_111() {
                return this.panelist_attr_111;
        }

        public void setPanelist_attr_111(Long panelist_attr_111) {
                this.panelist_attr_111 = panelist_attr_111;
        }

        public Long getPanelist_attr_112() {
                return this.panelist_attr_112;
        }

        public void setPanelist_attr_112(Long panelist_attr_112) {
                this.panelist_attr_112 = panelist_attr_112;
        }

        public Long getPanelist_attr_113() {
                return this.panelist_attr_113;
        }

        public void setPanelist_attr_113(Long panelist_attr_113) {
                this.panelist_attr_113 = panelist_attr_113;
        }

        public Long getPanelist_attr_114() {
                return this.panelist_attr_114;
        }

        public void setPanelist_attr_114(Long panelist_attr_114) {
                this.panelist_attr_114 = panelist_attr_114;
        }

        public Long getPanelist_attr_115() {
                return this.panelist_attr_115;
        }

        public void setPanelist_attr_115(Long panelist_attr_115) {
                this.panelist_attr_115 = panelist_attr_115;
        }

        public Long getPanelist_attr_116() {
                return this.panelist_attr_116;
        }

        public void setPanelist_attr_116(Long panelist_attr_116) {
                this.panelist_attr_116 = panelist_attr_116;
        }

        public Long getPanelist_attr_117() {
                return this.panelist_attr_117;
        }

        public void setPanelist_attr_117(Long panelist_attr_117) {
                this.panelist_attr_117 = panelist_attr_117;
        }

        public Long getPanelist_attr_118() {
                return this.panelist_attr_118;
        }

        public void setPanelist_attr_118(Long panelist_attr_118) {
                this.panelist_attr_118 = panelist_attr_118;
        }

        public Long getPanelist_attr_119() {
                return this.panelist_attr_119;
        }

        public void setPanelist_attr_119(Long panelist_attr_119) {
                this.panelist_attr_119 = panelist_attr_119;
        }

        public Long getPanelist_attr_120() {
                return this.panelist_attr_120;
        }

        public void setPanelist_attr_120(Long panelist_attr_120) {
                this.panelist_attr_120 = panelist_attr_120;
        }

        public Long getPanelist_attr_121() {
                return this.panelist_attr_121;
        }

        public void setPanelist_attr_121(Long panelist_attr_121) {
                this.panelist_attr_121 = panelist_attr_121;
        }

        public Long getPanelist_attr_122() {
                return this.panelist_attr_122;
        }

        public void setPanelist_attr_122(Long panelist_attr_122) {
                this.panelist_attr_122 = panelist_attr_122;
        }

        public Long getPanelist_attr_123() {
                return this.panelist_attr_123;
        }

        public void setPanelist_attr_123(Long panelist_attr_123) {
                this.panelist_attr_123 = panelist_attr_123;
        }

        public Long getPanelist_attr_124() {
                return this.panelist_attr_124;
        }

        public void setPanelist_attr_124(Long panelist_attr_124) {
                this.panelist_attr_124 = panelist_attr_124;
        }

        public Long getPanelist_attr_125() {
                return this.panelist_attr_125;
        }

        public void setPanelist_attr_125(Long panelist_attr_125) {
                this.panelist_attr_125 = panelist_attr_125;
        }

        public Long getPanelist_attr_126() {
                return this.panelist_attr_126;
        }

        public void setPanelist_attr_126(Long panelist_attr_126) {
                this.panelist_attr_126 = panelist_attr_126;
        }

        public Long getPanelist_attr_127() {
                return this.panelist_attr_127;
        }

        public void setPanelist_attr_127(Long panelist_attr_127) {
                this.panelist_attr_127 = panelist_attr_127;
        }

        public Long getPanelist_attr_128() {
                return this.panelist_attr_128;
        }

        public void setPanelist_attr_128(Long panelist_attr_128) {
                this.panelist_attr_128 = panelist_attr_128;
        }

        public Long getPanelist_attr_129() {
                return this.panelist_attr_129;
        }

        public void setPanelist_attr_129(Long panelist_attr_129) {
                this.panelist_attr_129 = panelist_attr_129;
        }

        public Long getPanelist_attr_130() {
                return this.panelist_attr_130;
        }

        public void setPanelist_attr_130(Long panelist_attr_130) {
                this.panelist_attr_130 = panelist_attr_130;
        }

        public Long getPanelist_attr_131() {
                return this.panelist_attr_131;
        }

        public void setPanelist_attr_131(Long panelist_attr_131) {
                this.panelist_attr_131 = panelist_attr_131;
        }

        public Long getPanelist_attr_132() {
                return this.panelist_attr_132;
        }

        public void setPanelist_attr_132(Long panelist_attr_132) {
                this.panelist_attr_132 = panelist_attr_132;
        }

        public Long getPanelist_attr_133() {
                return this.panelist_attr_133;
        }

        public void setPanelist_attr_133(Long panelist_attr_133) {
                this.panelist_attr_133 = panelist_attr_133;
        }

        public Long getPanelist_attr_134() {
                return this.panelist_attr_134;
        }

        public void setPanelist_attr_134(Long panelist_attr_134) {
                this.panelist_attr_134 = panelist_attr_134;
        }

        public Long getPanelist_attr_135() {
                return this.panelist_attr_135;
        }

        public void setPanelist_attr_135(Long panelist_attr_135) {
                this.panelist_attr_135 = panelist_attr_135;
        }

        public Long getPanelist_attr_136() {
                return this.panelist_attr_136;
        }

        public void setPanelist_attr_136(Long panelist_attr_136) {
                this.panelist_attr_136 = panelist_attr_136;
        }

        public Long getPanelist_attr_137() {
                return this.panelist_attr_137;
        }

        public void setPanelist_attr_137(Long panelist_attr_137) {
                this.panelist_attr_137 = panelist_attr_137;
        }

        public Long getPanelist_attr_138() {
                return this.panelist_attr_138;
        }

        public void setPanelist_attr_138(Long panelist_attr_138) {
                this.panelist_attr_138 = panelist_attr_138;
        }

        public Long getPanelist_attr_139() {
                return this.panelist_attr_139;
        }

        public void setPanelist_attr_139(Long panelist_attr_139) {
                this.panelist_attr_139 = panelist_attr_139;
        }

        public Long getPanelist_attr_140() {
                return this.panelist_attr_140;
        }

        public void setPanelist_attr_140(Long panelist_attr_140) {
                this.panelist_attr_140 = panelist_attr_140;
        }

        public Long getPanelist_attr_141() {
                return this.panelist_attr_141;
        }

        public void setPanelist_attr_141(Long panelist_attr_141) {
                this.panelist_attr_141 = panelist_attr_141;
        }

        public Long getPanelist_attr_142() {
                return this.panelist_attr_142;
        }

        public void setPanelist_attr_142(Long panelist_attr_142) {
                this.panelist_attr_142 = panelist_attr_142;
        }

        public Long getPanelist_attr_143() {
                return this.panelist_attr_143;
        }

        public void setPanelist_attr_143(Long panelist_attr_143) {
                this.panelist_attr_143 = panelist_attr_143;
        }

        public Long getPanelist_attr_144() {
                return this.panelist_attr_144;
        }

        public void setPanelist_attr_144(Long panelist_attr_144) {
                this.panelist_attr_144 = panelist_attr_144;
        }

        public Long getPanelist_attr_145() {
                return this.panelist_attr_145;
        }

        public void setPanelist_attr_145(Long panelist_attr_145) {
                this.panelist_attr_145 = panelist_attr_145;
        }

        public Long getPanelist_attr_146() {
                return this.panelist_attr_146;
        }

        public void setPanelist_attr_146(Long panelist_attr_146) {
                this.panelist_attr_146 = panelist_attr_146;
        }

        public Long getPanelist_attr_147() {
                return this.panelist_attr_147;
        }

        public void setPanelist_attr_147(Long panelist_attr_147) {
                this.panelist_attr_147 = panelist_attr_147;
        }

        public Long getPanelist_attr_148() {
                return this.panelist_attr_148;
        }

        public void setPanelist_attr_148(Long panelist_attr_148) {
                this.panelist_attr_148 = panelist_attr_148;
        }

        public Long getPanelist_attr_149() {
                return this.panelist_attr_149;
        }

        public void setPanelist_attr_149(Long panelist_attr_149) {
                this.panelist_attr_149 = panelist_attr_149;
        }

        public Long getPanelist_attr_150() {
                return this.panelist_attr_150;
        }

        public void setPanelist_attr_150(Long panelist_attr_150) {
                this.panelist_attr_150 = panelist_attr_150;
        }

        public Long getPanelist_attr_151() {
                return this.panelist_attr_151;
        }

        public void setPanelist_attr_151(Long panelist_attr_151) {
                this.panelist_attr_151 = panelist_attr_151;
        }

        public Long getPanelist_attr_152() {
                return this.panelist_attr_152;
        }

        public void setPanelist_attr_152(Long panelist_attr_152) {
                this.panelist_attr_152 = panelist_attr_152;
        }

        public Long getPanelist_attr_153() {
                return this.panelist_attr_153;
        }

        public void setPanelist_attr_153(Long panelist_attr_153) {
                this.panelist_attr_153 = panelist_attr_153;
        }

        public Long getPanelist_attr_154() {
                return this.panelist_attr_154;
        }

        public void setPanelist_attr_154(Long panelist_attr_154) {
                this.panelist_attr_154 = panelist_attr_154;
        }

        public Long getPanelist_attr_155() {
                return this.panelist_attr_155;
        }

        public void setPanelist_attr_155(Long panelist_attr_155) {
                this.panelist_attr_155 = panelist_attr_155;
        }

        public Long getPanelist_attr_156() {
                return this.panelist_attr_156;
        }

        public void setPanelist_attr_156(Long panelist_attr_156) {
                this.panelist_attr_156 = panelist_attr_156;
        }

        public Long getPanelist_attr_157() {
                return this.panelist_attr_157;
        }

        public void setPanelist_attr_157(Long panelist_attr_157) {
                this.panelist_attr_157 = panelist_attr_157;
        }

        public Long getPanelist_attr_158() {
                return this.panelist_attr_158;
        }

        public void setPanelist_attr_158(Long panelist_attr_158) {
                this.panelist_attr_158 = panelist_attr_158;
        }

        public Long getPanelist_attr_159() {
                return this.panelist_attr_159;
        }

        public void setPanelist_attr_159(Long panelist_attr_159) {
                this.panelist_attr_159 = panelist_attr_159;
        }

        public String getQuestionnaire_values_04() {
                return this.questionnaire_values_04;
        }

        public void setQuestionnaire_values_04(String questionnaire_values_04) {
                this.questionnaire_values_04 = questionnaire_values_04;
        }

        public java.util.List<java.lang.Long> getSdr_primary_key() {
                return this.sdr_primary_key;
        }

        public void setSdr_primary_key(java.util.List<java.lang.Long> sdr_primary_key) {
                this.sdr_primary_key = sdr_primary_key;
        }

        public String getEnd_of_rec() {
                return this.end_of_rec;
        }

        public void setEnd_of_rec(String end_of_rec) {
                this.end_of_rec = end_of_rec;
        }



	
	/*
	 * public cns_panelist_datamodel(java.lang.String country, java.lang.String
	 * business) { this.country = country; this.business = business; }
	 */

}