package com.panelist_rm.panelist;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class dim_levels implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public dim_levels() {
    }




}